Add smart-push and smart-pull with squash

diff --git a/git-smart-pull b/git-smart-pull
--- a/git-smart-pull
+++ b/git-smart-pull
@@ -3,38 +3,38 @@
 set -euo pipefail
 
 function log {
-  echo >&2 "$@"
+  echo >&2 "[smart-pull]" "$@"
 }
 
 set +e
 if [ "$(tput colors 2>/dev/null)" -ge 8 ]; then
   function log {
     printf >&2 "\033[90m"
-    echo   >&2 "$@"
+    echo   >&2 "[smart-pull]" "$@"
     printf >&2 "\033[0m"
   }
 fi
 set -e
 
-log "[smart-pull] Attempting fast-forward pull"
+log "Attempting fast-forward pull"
 set +e
 git pull --ff-only "$@" 2>/dev/null
 res=$?
 set -e
 
 if [ $res -eq 0 ]; then
-  log "[smart-pull] Fast-forward pull succeeded."
+  log "Fast-forward pull succeeded."
   exit 0
 elif [ $res -ne 128 ]; then
-  log "[smart-pull] git pull exited with unexpected status $res"
-  log "[smart-pull] Re-running it so you can see the output:"
+  log "git pull exited with unexpected status $res"
+  log "Re-running it so you can see the output:"
   git pull --ff-only "$@"
 fi
 
-log "[smart-pull] Fast-forward pull failed."
-log ["smart-pull] Checking if we can rebase without conflict."
+log "Fast-forward pull failed."
+log "Checking if we can rebase without conflict."
 if ! git diff --quiet --ignore-submodules || ! git diff --staged --quiet; then
-  log "[smart-pull] Dirty working tree or index. Aborting."
+  log "Dirty working tree or index. Aborting."
   exit 2
 fi
 upstream_branch="$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}")"
@@ -46,34 +46,60 @@ git pull --rebase=true >/dev/null 2>/dev/null
 rebase_ok=$?
 set -e
 if [ $rebase_ok -eq 0 ]; then
-  log "[smart-pull] Can rebase without conflict."
-  log "[smart-pull] Will pull with rebase."
+  log "Can rebase without conflict."
+  log "Will pull with rebase."
   git checkout -
   git branch -D _git-smart-pull --quiet 2>/dev/null || true
   git pull --rebase=true
 else
-  log "[smart-pull] Cannot rebase without conflict. Conflicted files:"
+  log "Cannot rebase without conflict. Conflicted files:"
   ( 
     IFS=$'\n'
     for f in $(git diff --name-only --diff-filter=U --relative); do
-      log "[smart-pull] $f"
+      log "$f"
     done
   )
   git rebase --abort
   git checkout - --quiet
   git branch -D _git-smart-pull --quiet 2>/dev/null || true
   while true; do
-    read -r -p "Select pull method: [m]erge / [r]ebase / [n]one " res
+    read -r -p "Select pull method: [m]erge / [r]ebase / [q]uit " res
     case $res in
       m)
         exec git pull --rebase=no
         break
         ;;
       r)
+        upstream="$(git rev-parse --abbrev-ref "@{u}")"
+        merge_base="$(git merge-base HEAD "$upstream")"
+        if [ "$(git rev-list --count "$merge_base"..)" -gt 1 ]; then
+          echo >&2 "Commits to be rebased:"
+          git log --oneline "$merge_base"..
+          while true; do
+            read -r -p "Do you want to squash the commits before rebasing? [s]quash / [i]nteractive rebase / [n]o " res
+            case $res in
+              s)
+                first_commit_after_merge_base="$(git rev-list --reverse "$merge_base".. | head -n 1)"
+                git reset --soft "$first_commit_after_merge_base"
+                git add -A
+                git commit --amend
+                break
+                ;;
+              i)
+                git rebase -i "$merge_base"
+                break
+                ;;
+              n)
+                break
+                ;;
+              *) ;;
+          esac
+        done
+      fi
         exec git pull --rebase=yes
         break
         ;;
-      [n])
+      q)
         exit 1
         ;;
       *) ;;
