Add smart-rebase

diff --git a/git-smart-pull b/git-smart-pull
--- a/git-smart-pull
+++ b/git-smart-pull
@@ -6,6 +6,10 @@ function log {
   echo >&2 "[smart-pull]" "$@"
 }
 
+function err {
+  echo >&2 "[smart-pull]" "$@"
+}
+
 set +e
 if [ "$(tput colors 2>/dev/null)" -ge 8 ]; then
   function log {
@@ -13,12 +17,29 @@ if [ "$(tput colors 2>/dev/null)" -ge 8 ]; then
     echo   >&2 "[smart-pull]" "$@"
     printf >&2 "\033[0m"
   }
+
+  function err {
+    printf >&2 "\033[31m"
+    echo   >&2 "[smart-pull]" "$@"
+    printf >&2 "\033[0m"
+  }
 fi
 set -e
 
+if [ -n "${2:-}" ]; then
+  err "Upstream argument not supported. It is always 'origin'."
+  exit 1
+fi
+
+if [ -n "${1:-}" ]; then
+  args="origin $1"
+else
+  args=""
+fi
+
 log "Attempting fast-forward pull"
 set +e
-git pull --ff-only "$@" 2>/dev/null
+git pull --ff-only $args 2>/dev/null
 res=$?
 set -e
 
@@ -26,23 +47,23 @@ if [ $res -eq 0 ]; then
   log "Fast-forward pull succeeded."
   exit 0
 elif [ $res -ne 128 ]; then
-  log "git pull exited with unexpected status $res"
-  log "Re-running it so you can see the output:"
-  git pull --ff-only "$@"
+  err "git pull exited with unexpected status $res"
+  err "Re-running it so you can see the output:"
+  git pull --ff-only $args
 fi
 
 log "Fast-forward pull failed."
 log "Checking if we can rebase without conflict."
 if ! git diff --quiet --ignore-submodules || ! git diff --staged --quiet; then
-  log "Dirty working tree or index. Aborting."
+  err "Dirty working tree or index. Aborting."
   exit 2
 fi
-upstream_branch="$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}")"
+upstream_branch="$(git rev-parse --abbrev-ref "@{u}")"
 git branch -D _git-smart-pull --quiet 2>/dev/null || true
 git checkout -b _git-smart-pull --quiet
 git branch --set-upstream-to "$upstream_branch" --quiet
 set +e
-git pull --rebase=true >/dev/null 2>/dev/null
+git pull --rebase=true $args >/dev/null 2>/dev/null
 rebase_ok=$?
 set -e
 if [ $rebase_ok -eq 0 ]; then
@@ -50,7 +71,7 @@ if [ $rebase_ok -eq 0 ]; then
   log "Will pull with rebase."
   git checkout -
   git branch -D _git-smart-pull --quiet 2>/dev/null || true
-  git pull --rebase=true
+  git pull --rebase=true $args
 else
   log "Cannot rebase without conflict. Conflicted files:"
   ( 
@@ -66,37 +87,17 @@ else
     read -r -p "Select pull method: [m]erge / [r]ebase / [q]uit " res
     case $res in
       m)
-        exec git pull --rebase=no
+        exec git pull --rebase=no $args
         break
         ;;
       r)
-        upstream="$(git rev-parse --abbrev-ref "@{u}")"
-        merge_base="$(git merge-base HEAD "$upstream")"
-        if [ "$(git rev-list --count "$merge_base"..)" -gt 1 ]; then
-          echo >&2 "Commits to be rebased:"
-          git log --oneline "$merge_base"..
-          while true; do
-            read -r -p "Do you want to squash the commits before rebasing? [s]quash / [i]nteractive rebase / [n]o " res
-            case $res in
-              s)
-                first_commit_after_merge_base="$(git rev-list --reverse "$merge_base".. | head -n 1)"
-                git reset --soft "$first_commit_after_merge_base"
-                git add -A
-                git commit --amend
-                break
-                ;;
-              i)
-                git rebase -i "$merge_base"
-                break
-                ;;
-              n)
-                break
-                ;;
-              *) ;;
-          esac
-        done
-      fi
-        exec git pull --rebase=yes
+        git fetch -a
+        if [ -n "${1:-}" ]; then
+          rebase_branch="origin/$1"
+        else
+          rebase_branch="$upstream_branch"
+        fi
+        exec git smart-rebase "$rebase_branch"
         break
         ;;
       q)
